
// Embedded JSON data for products
export const productsData = {
  "Hardware and Plastic": [
    {"sno": 1, "productName": "Plastic Balti 8 Ltr", "buyingPrice": "₹300", "sellingPrice": "₹65-70", "unit": "8 Ltr", "nos": 5},
    {"sno": 2, "productName": "Plastic Balti 10 Ltr", "buyingPrice": "₹400", "sellingPrice": "₹85-90", "unit": "10 Ltr", "nos": 5},
    {"sno": 3, "productName": "Plastic Balti 15 Ltr", "buyingPrice": "₹475", "sellingPrice": "₹100-110", "unit": "15 Ltr", "nos": 5},
    {"sno": 4, "productName": "Plastic Balti 20 Ltr", "buyingPrice": "₹625", "sellingPrice": "₹130-140", "unit": "20 Ltr", "nos": 5},
    {"sno": 5, "productName": "Tagari (Plastic) Small", "buyingPrice": "₹375", "sellingPrice": "₹85-90", "unit": "Piece", "nos": 1},
    {"sno": 6, "productName": "Tagari (Plastic) Big", "buyingPrice": "₹425", "sellingPrice": "₹95-100", "unit": "Piece", "nos": 1},
    {"sno": 7, "productName": "Gamla (Plastic) 160mm", "buyingPrice": "₹510", "sellingPrice": "₹95-100", "unit": "160mm", "nos": 6},
    {"sno": 8, "productName": "Gamla (Plastic) 170mm", "buyingPrice": "₹600", "sellingPrice": "₹110-120", "unit": "170mm", "nos": 6},
    {"sno": 9, "productName": "Gamla (Plastic) 200mm", "buyingPrice": "₹780", "sellingPrice": "₹140-145", "unit": "200mm", "nos": 6},
    {"sno": 10, "productName": "Masking Tape 1\"", "buyingPrice": "₹110", "sellingPrice": "₹12", "unit": "1\" Roll", "nos": 6},
    {"sno": 11, "productName": "Masking Tape 1/2\"", "buyingPrice": "₹110", "sellingPrice": "₹13", "unit": "1/2\" Roll", "nos": 8},
    {"sno": 12, "productName": "Masking Tape 2\"", "buyingPrice": "₹330", "sellingPrice": "₹30", "unit": "2\" Roll", "nos": 6},
    {"sno": 13, "productName": "Ultra PVC Tape 2\"", "buyingPrice": "₹190", "sellingPrice": "₹30", "unit": "2\" Roll", "nos": 6},
    {"sno": 14, "productName": "Ayushi Bracket Pair", "buyingPrice": "₹840", "sellingPrice": "₹30-50", "unit": "Pair", "nos": 28},
    {"sno": 15, "productName": "Kalwar Bracket Pair", "buyingPrice": "₹750", "sellingPrice": "₹125-130", "unit": "Pair", "nos": 10},
    {"sno": 16, "productName": "Curtain Pipe 1\"", "buyingPrice": "₹240", "sellingPrice": "₹170-240", "unit": "Per Feet", "nos": 3},
    {"sno": 17, "productName": "Curtain Pipe 3/4\"", "buyingPrice": "₹180", "sellingPrice": "₹120-180", "unit": "Per Feet", "nos": 3},
    {"sno": 18, "productName": "Silicon", "buyingPrice": "₹720", "sellingPrice": "₹150", "unit": "Bottle", "nos": 6},
    {"sno": 19, "productName": "Padlock (Tala) 30mm", "buyingPrice": "₹300", "sellingPrice": "₹50", "unit": "30mm", "nos": 10},
    {"sno": 20, "productName": "Padlock (Tala) 52mm", "buyingPrice": "₹300", "sellingPrice": "₹90", "unit": "52mm", "nos": 5},
    {"sno": 21, "productName": "Padlock (Tala) 65mm", "buyingPrice": "₹550", "sellingPrice": "₹160-170", "unit": "65mm", "nos": 5},
    {"sno": 22, "productName": "Karkat Nut", "buyingPrice": "₹120", "sellingPrice": "₹3", "unit": "Piece", "nos": 60},
    {"sno": 23, "productName": "Karkat Washer", "buyingPrice": "₹180", "sellingPrice": "₹4", "unit": "Piece", "nos": 60}
  ],
  "Valve & Nal": [
    {"sno": 1, "productName": "CPVC Cancelled Valve 3/4\"", "buyingPrice": "₹2847", "sellingPrice": "₹1358-1400", "unit": "3/4\" Piece", "nos": 3},
    {"sno": 2, "productName": "UPVC Cancelled Valve 3/4\"", "buyingPrice": "₹5758", "sellingPrice": "₹1050-1150", "unit": "3/4\" Piece", "nos": 6},
    {"sno": 3, "productName": "Check Valve 1\"", "buyingPrice": "₹840", "sellingPrice": "₹160-170", "unit": "1\" Piece", "nos": 6},
    {"sno": 4, "productName": "Nall (Plastic) 1/2\" S(PVC)", "buyingPrice": "₹450", "sellingPrice": "₹60-65", "unit": "1/2\" Piece", "nos": 12},
    {"sno": 5, "productName": "Nall (Plastic) 1/2\" L(PVC)", "buyingPrice": "₹550", "sellingPrice": "₹75-80", "unit": "1/2\" Piece", "nos": 12},
    {"sno": 6, "productName": "Angle Valve 1/2\" (CP)", "buyingPrice": "₹700", "sellingPrice": "₹90-95", "unit": "1/2\" Piece", "nos": 10},
    {"sno": 7, "productName": "Hand Spray (steel)(CP)", "buyingPrice": "₹2760", "sellingPrice": "₹550-600", "unit": "Piece", "nos": 2},
    {"sno": 8, "productName": "Basin Pillar Cock 1/2\" (Supreme)", "buyingPrice": "₹502", "sellingPrice": "₹665", "unit": "1/2\" Piece", "nos": 1},
    {"sno": 9, "productName": "Basin Pillar Cock 1/2\" (PVC Polyworld)", "buyingPrice": "₹410", "sellingPrice": "₹325", "unit": "1/2\" Piece", "nos": 2},
    {"sno": 10, "productName": "Basin Pillar Cock 1/2\" (Supreme)", "buyingPrice": "₹540", "sellingPrice": "₹320", "unit": "1/2\" Piece", "nos": 2},
    {"sno": 11, "productName": "Sink Cock 1/2\" (PVC Polyworld)", "buyingPrice": "₹410", "sellingPrice": "₹360", "unit": "1/2\" Piece", "nos": 2},
    {"sno": 12, "productName": "Bath Shower Mixer (CP)", "buyingPrice": "₹4900", "sellingPrice": "₹2850-3100", "unit": "Piece", "nos": 2},
    {"sno": 13, "productName": "Basin Mixer (CP)", "buyingPrice": "₹3900", "sellingPrice": "₹2500-2550", "unit": "Piece", "nos": 2},
    {"sno": 14, "productName": "Swan Neck Pillar Cock (CP)", "buyingPrice": "₹1200", "sellingPrice": "₹900", "unit": "Piece", "nos": 2},
    {"sno": 15, "productName": "Sink Cock Single (CP)", "buyingPrice": "₹1200", "sellingPrice": "₹900", "unit": "Piece", "nos": 2},
    {"sno": 16, "productName": "Sink Aashirwad (24x18)", "buyingPrice": "₹1050", "sellingPrice": "₹1450-1500", "unit": "24x18 Piece", "nos": 1},
    {"sno": 17, "productName": "Sink Centux (24x18)", "buyingPrice": "₹1630", "sellingPrice": "₹1950-2100", "unit": "24x18 Piece", "nos": 1},
    {"sno": 18, "productName": "Sink Mixer (Kitchen)", "buyingPrice": "₹2150", "sellingPrice": "₹2450", "unit": "Piece", "nos": 1},
    {"sno": 19, "productName": "Angle Valve (Plastic) 1/2\"", "buyingPrice": "₹1230", "sellingPrice": "₹245", "unit": "1/2\" Piece", "nos": 6},
    {"sno": 20, "productName": "Hand Spray (PVC Plasto)", "buyingPrice": "₹820", "sellingPrice": "₹480-490", "unit": "Piece", "nos": 2},
    {"sno": 21, "productName": "Hand Spray (PVC Supreme)", "buyingPrice": "₹610", "sellingPrice": "₹350", "unit": "Piece", "nos": 2},
    {"sno": 22, "productName": "Angle Valve (Two-in-One)", "buyingPrice": "₹610", "sellingPrice": "₹370", "unit": "Piece", "nos": 2}
  ],
  "Tools": [
    {"sno": 1, "productName": "Hand Saw (Aarri)", "buyingPrice": "₹140", "sellingPrice": "₹85-90", "unit": "Piece", "nos": 2},
    {"sno": 2, "productName": "Measuring Tape 3m", "buyingPrice": "₹400", "sellingPrice": "₹50-55", "unit": "3m Piece", "nos": 10},
    {"sno": 3, "productName": "Measuring Tape 5m", "buyingPrice": "₹600", "sellingPrice": "₹70-75", "unit": "5m Piece", "nos": 10},
    {"sno": 4, "productName": "Karni 1 No", "buyingPrice": "₹360", "sellingPrice": "₹70-75", "unit": "Piece", "nos": 6},
    {"sno": 5, "productName": "Karni 2 No", "buyingPrice": "₹360", "sellingPrice": "₹70-75", "unit": "Piece", "nos": 6},
    {"sno": 6, "productName": "Karni 3 No", "buyingPrice": "₹300", "sellingPrice": "₹60-65", "unit": "Piece", "nos": 6},
    {"sno": 7, "productName": "Sahul", "buyingPrice": "₹330", "sellingPrice": "₹65-70", "unit": "Piece", "nos": 6},
    {"sno": 8, "productName": "Russa (Gulmala)", "buyingPrice": "₹480", "sellingPrice": "₹50-60", "unit": "Piece", "nos": 12},
    {"sno": 9, "productName": "Blade (Hack Saw)", "buyingPrice": "₹350", "sellingPrice": "₹7-10", "unit": "Piece", "nos": 50},
    {"sno": 10, "productName": "Hack Saw Frame", "buyingPrice": "₹400", "sellingPrice": "₹80-90", "unit": "Piece", "nos": 6},
    {"sno": 11, "productName": "Hammer & Handle 1kg", "buyingPrice": "₹560", "sellingPrice": "₹170", "unit": "1kg Piece", "nos": 4},
    {"sno": 12, "productName": "Shuttering Hammer (Claw Hammer)", "buyingPrice": "₹540", "sellingPrice": "₹90-110", "unit": "Piece", "nos": 6},
    {"sno": 13, "productName": "Basuli (Hammer) Handle", "buyingPrice": "₹360", "sellingPrice": "₹90-100", "unit": "Piece", "nos": 4},
    {"sno": 14, "productName": "Basuli (Non-Handle)", "buyingPrice": "₹240", "sellingPrice": "₹80-90", "unit": "Piece", "nos": 4},
    {"sno": 15, "productName": "Magnet Bits", "buyingPrice": "₹100", "sellingPrice": "₹30-40", "unit": "Piece", "nos": 5},
    {"sno": 16, "productName": "Sahul Dhaga", "buyingPrice": "₹100", "sellingPrice": "₹12-15", "unit": "Piece", "nos": 10},
    {"sno": 17, "productName": "Lime Dorri", "buyingPrice": "₹90", "sellingPrice": "₹8-10", "unit": "Piece", "nos": 12},
    {"sno": 18, "productName": "Level Pipe (Water) Perfect", "buyingPrice": "₹580", "sellingPrice": "₹130-140", "unit": "Piece", "nos": 5},
    {"sno": 19, "productName": "Cheni (Chisel) 6\"", "buyingPrice": "₹120", "sellingPrice": "₹80", "unit": "6\" Piece", "nos": 2},
    {"sno": 20, "productName": "Cheni (Chisel) 8\"", "buyingPrice": "₹160", "sellingPrice": "₹100", "unit": "8\" Piece", "nos": 2},
    {"sno": 21, "productName": "Cheni (Chisel) 10\"", "buyingPrice": "₹200", "sellingPrice": "₹120", "unit": "10\" Piece", "nos": 2},
    {"sno": 22, "productName": "Spanner Set", "buyingPrice": "₹455", "sellingPrice": "₹300", "unit": "Set", "nos": 2},
    {"sno": 23, "productName": "Adjustable Spanner 10\"", "buyingPrice": "₹280", "sellingPrice": "₹200", "unit": "10\" Piece", "nos": 2},
    {"sno": 24, "productName": "Speed Level 12\"", "buyingPrice": "₹180", "sellingPrice": "₹90-120", "unit": "12\" Piece", "nos": 2},
    {"sno": 25, "productName": "Speed Level 7\"", "buyingPrice": "₹140", "sellingPrice": "₹100", "unit": "7\" Piece", "nos": 2},
    {"sno": 26, "productName": "Screw Driver (Pechkas) (+-) 8\"", "buyingPrice": "₹130", "sellingPrice": "₹80-90", "unit": "8\" Piece", "nos": 2},
    {"sno": 27, "productName": "Silicon Gun", "buyingPrice": "₹120", "sellingPrice": "₹220", "unit": "Piece", "nos": 1},
    {"sno": 28, "productName": "Concrete Bits 6mm (SD)", "buyingPrice": "₹90", "sellingPrice": "₹60", "unit": "6mm Piece", "nos": 2},
    {"sno": 29, "productName": "Concrete Bits 8mm (SD)", "buyingPrice": "₹120", "sellingPrice": "₹80", "unit": "8mm Piece", "nos": 2},
    {"sno": 30, "productName": "Concrete Bits 10mm (SD)", "buyingPrice": "₹130", "sellingPrice": "₹100", "unit": "10mm Piece", "nos": 2},
    {"sno": 31, "productName": "Concrete Bits 12mm (SD)", "buyingPrice": "₹160", "sellingPrice": "₹120", "unit": "12mm Piece", "nos": 2},
    {"sno": 32, "productName": "Concrete Bits 6mm (Normal)", "buyingPrice": "₹88", "sellingPrice": "₹50", "unit": "6mm Piece", "nos": 2},
    {"sno": 33, "productName": "Concrete Bits 8mm (Normal)", "buyingPrice": "₹70", "sellingPrice": "₹40", "unit": "8mm Piece", "nos": 2},
    {"sno": 34, "productName": "HS Bits (Loha) 4mm", "buyingPrice": "₹80", "sellingPrice": "₹40", "unit": "4mm Piece", "nos": 2},
    {"sno": 35, "productName": "HS Bits (Loha) 6mm", "buyingPrice": "₹80", "sellingPrice": "₹70", "unit": "6mm Piece", "nos": 2},
    {"sno": 36, "productName": "HS Bits (Loha) 8mm", "buyingPrice": "₹120", "sellingPrice": "₹80", "unit": "8mm Piece", "nos": 2},
    {"sno": 37, "productName": "Measuring Tape 15m", "buyingPrice": "₹160", "sellingPrice": "₹160", "unit": "15m Piece", "nos": 1},
    {"sno": 38, "productName": "Pliers (Plair)", "buyingPrice": "₹280", "sellingPrice": "₹250", "unit": "Piece", "nos": 2},
    {"sno": 39, "productName": "Kudal", "buyingPrice": "₹460", "sellingPrice": "₹300", "unit": "Piece", "nos": 2},
    {"sno": 40, "productName": "Belcha", "buyingPrice": "₹560", "sellingPrice": "₹350-370", "unit": "Piece", "nos": 2},
    {"sno": 41, "productName": "Grinder Machine", "buyingPrice": "₹2500", "sellingPrice": "₹1500", "unit": "Piece", "nos": 2}
  ],
  "SWR-Fitting": [
    {"sno": 1, "productName": "SWR Pipe 4\" (Aashirwad)", "buyingPrice": "₹4600", "sellingPrice": "₹460", "unit": "4\" Piece", "nos": 10},
    {"sno": 2, "productName": "SWR Pipe 3\" (Aashirwad)", "buyingPrice": "₹2700", "sellingPrice": "₹270-300", "unit": "3\" Piece", "nos": 10},
    {"sno": 3, "productName": "SWR Pipe 4\" (Gupta)", "buyingPrice": "₹2350", "sellingPrice": "₹235-260", "unit": "4\" Piece", "nos": 10},
    {"sno": 4, "productName": "SWR Pipe 3\" (Gupta)", "buyingPrice": "₹1350", "sellingPrice": "₹135-170", "unit": "3\" Piece", "nos": 10},
    {"sno": 5, "productName": "SWR Elbow 4\" 90°", "buyingPrice": "₹700", "sellingPrice": "₹70-85", "unit": "4\" Piece", "nos": 10},
    {"sno": 6, "productName": "SWR Elbow 3\" 90°", "buyingPrice": "₹350", "sellingPrice": "₹35-50", "unit": "3\" Piece", "nos": 10},
    {"sno": 7, "productName": "SWR Tee 4\" 90deg", "buyingPrice": "₹1050", "sellingPrice": "₹105-120", "unit": "4\" Piece", "nos": 10},
    {"sno": 8, "productName": "SWR Tee 3\" 90deg", "buyingPrice": "₹600", "sellingPrice": "₹60-75", "unit": "3\" Piece", "nos": 10},
    {"sno": 9, "productName": "SWR Elbow 4\" 45°", "buyingPrice": "₹600", "sellingPrice": "₹60-85", "unit": "4\" Piece", "nos": 10},
    {"sno": 10, "productName": "SWR Elbow 3\" 45°", "buyingPrice": "₹320", "sellingPrice": "₹32-60", "unit": "3\" Piece", "nos": 10},
    {"sno": 11, "productName": "SWR Socket 4\" 45deg", "buyingPrice": "₹550", "sellingPrice": "₹55-75", "unit": "4\" Piece", "nos": 10},
    {"sno": 12, "productName": "SWR Socket 3\" 45deg", "buyingPrice": "₹350", "sellingPrice": "₹35-60", "unit": "3\" Piece", "nos": 10},
    {"sno": 13, "productName": "SWR Y-Tee 4\" 45deg", "buyingPrice": "₹1350", "sellingPrice": "₹135-165", "unit": "4\" Piece", "nos": 10},
    {"sno": 14, "productName": "SWR Y-Tee 3\" 45deg", "buyingPrice": "₹750", "sellingPrice": "₹75-100", "unit": "3\" Piece", "nos": 10},
    {"sno": 15, "productName": "SWR P-Trap (Murga) 4\"", "buyingPrice": "₹960", "sellingPrice": "₹160-200", "unit": "4\" Piece", "nos": 6},
    {"sno": 16, "productName": "SWR Nahani Trap 4\"x3\"", "buyingPrice": "₹450", "sellingPrice": "₹75-95", "unit": "4\"x3\" Piece", "nos": 6},
    {"sno": 17, "productName": "SWR End Cap 4\"", "buyingPrice": "₹350", "sellingPrice": "₹35-50", "unit": "4\" Piece", "nos": 10},
    {"sno": 18, "productName": "SWR End Cap 3\"", "buyingPrice": "₹300", "sellingPrice": "₹30-45", "unit": "3\" Piece", "nos": 10},
    {"sno": 19, "productName": "SWR Reducing Socket 4\"x3\"", "buyingPrice": "₹450", "sellingPrice": "₹50-70", "unit": "4\"x3\" Piece", "nos": 10},
    {"sno": 20, "productName": "SWR Door Elbow 4\"", "buyingPrice": "₹540", "sellingPrice": "₹95-110", "unit": "4\" Piece", "nos": 6},
    {"sno": 21, "productName": "SWR Door Elbow 3\"", "buyingPrice": "₹300", "sellingPrice": "₹60-80", "unit": "3\" Piece", "nos": 6},
    {"sno": 22, "productName": "SWR Door Tee 4\"", "buyingPrice": "₹780", "sellingPrice": "₹155-180", "unit": "4\" Piece", "nos": 6},
    {"sno": 23, "productName": "SWR Door Tee 3\"", "buyingPrice": "₹450", "sellingPrice": "₹85-95", "unit": "3\" Piece", "nos": 6},
    {"sno": 24, "productName": "SWR Gas Topi 4\"", "buyingPrice": "₹210", "sellingPrice": "₹40-45", "unit": "4\" Piece", "nos": 6},
    {"sno": 25, "productName": "SWR Gas Topi 3\"", "buyingPrice": "₹150", "sellingPrice": "₹30-35", "unit": "3\" Piece", "nos": 6}
  ],
  "GI Fitting": [
    {"sno": 1, "productName": "GI Bend 1\"", "buyingPrice": "₹200", "sellingPrice": "₹30", "unit": "1\" Piece", "nos": 6},
    {"sno": 2, "productName": "GI Tee 1/2\"x1\"", "buyingPrice": "₹800", "sellingPrice": "₹80-90", "unit": "1/2\"x1\" Piece", "nos": 10},
    {"sno": 3, "productName": "GI Tee 1/2\"x1\"", "buyingPrice": "₹650", "sellingPrice": "₹130-140", "unit": "1/2\"x1\" Piece", "nos": 5},
    {"sno": 4, "productName": "GI Elbow 1/2\"", "buyingPrice": "₹550", "sellingPrice": "₹110-120", "unit": "1/2\" Piece", "nos": 5},
    {"sno": 5, "productName": "GI Nipple 1/2\"", "buyingPrice": "₹210", "sellingPrice": "₹35-45", "unit": "1/2\" Piece", "nos": 6},
    {"sno": 6, "productName": "GI Nipple 1\"", "buyingPrice": "₹168", "sellingPrice": "₹30-35", "unit": "1\" Piece", "nos": 6},
    {"sno": 7, "productName": "GI Socket 1/2\"", "buyingPrice": "₹550", "sellingPrice": "₹56-70", "unit": "1/2\" Piece", "nos": 10},
    {"sno": 8, "productName": "GI Nipple 1/2\"", "buyingPrice": "₹330", "sellingPrice": "₹60-70", "unit": "1/2\" Piece", "nos": 8}
  ],
  "Tools & Hardware": [
    {"sno": 1, "productName": "Hanger 6 Khutti", "buyingPrice": "₹480", "sellingPrice": "₹45-50", "unit": "Piece", "nos": 12},
    {"sno": 2, "productName": "Hanger 6 Khutli", "buyingPrice": "₹1200", "sellingPrice": "₹180-200", "unit": "Piece", "nos": 10},
    {"sno": 3, "productName": "Hose Clips 3/4\"", "buyingPrice": "₹60", "sellingPrice": "₹5-6", "unit": "3/4\" Piece", "nos": 20},
    {"sno": 4, "productName": "Taar Brush (Wood)", "buyingPrice": "₹360", "sellingPrice": "₹40-50", "unit": "Piece", "nos": 12},
    {"sno": 5, "productName": "Kudaal", "buyingPrice": "₹460", "sellingPrice": "₹280-300", "unit": "Piece", "nos": 2},
    {"sno": 6, "productName": "Belcha", "buyingPrice": "₹560", "sellingPrice": "₹350-370", "unit": "Piece", "nos": 2},
    {"sno": 7, "productName": "Reti (File)", "buyingPrice": "₹150", "sellingPrice": "₹50-55", "unit": "Piece", "nos": 5},
    {"sno": 8, "productName": "Water Paper (Emery Paper)", "buyingPrice": "₹96", "sellingPrice": "₹10-12", "unit": "Piece", "nos": 12},
    {"sno": 9, "productName": "Taggadi GI", "buyingPrice": "₹460", "sellingPrice": "₹125-130", "unit": "Piece", "nos": 5},
    {"sno": 10, "productName": "White Cement 1kg", "buyingPrice": "₹620", "sellingPrice": "₹40-45", "unit": "1kg Packet", "nos": 25},
    {"sno": 11, "productName": "Gamla GI", "buyingPrice": "₹377", "sellingPrice": "₹145-150", "unit": "Piece", "nos": 3},
    {"sno": 12, "productName": "Balu Jalli 3 Feet", "buyingPrice": "₹900", "sellingPrice": "₹330-340", "unit": "Per Feet", "nos": 3},
    {"sno": 13, "productName": "Toilet Brush", "buyingPrice": "₹360", "sellingPrice": "₹40-45", "unit": "Piece", "nos": 12},
    {"sno": 14, "productName": "Kalampu 4-5kg", "buyingPrice": "₹350", "sellingPrice": "₹80 /kg", "unit": "4-5kg Piece", "nos": 1},
    {"sno": 15, "productName": "Welding Rod (Mangal) 2.5mm", "buyingPrice": "₹1700", "sellingPrice": "₹280-300", "unit": "Box Packet", "nos": 6},
    {"sno": 16, "productName": "Narkul Rassi", "buyingPrice": "₹700", "sellingPrice": "₹90 /kg", "unit": "Per kg", "nos": 1},
    {"sno": 17, "productName": "Karkat Bolt 1\" (500pcs)", "buyingPrice": "₹900", "sellingPrice": "₹3", "unit": "Piece", "nos": 500},
    {"sno": 18, "productName": "Karkat Bolt 1/2\" (500pcs)", "buyingPrice": "₹950", "sellingPrice": "₹3.50", "unit": "Piece", "nos": 500},
    {"sno": 19, "productName": "Fastener 8mm", "buyingPrice": "₹192", "sellingPrice": "₹15", "unit": "Piece", "nos": 50},
    {"sno": 20, "productName": "Fastener 10mm", "buyingPrice": "₹288", "sellingPrice": "₹20", "unit": "Piece", "nos": 50},
    {"sno": 21, "productName": "Washer 3 Suta (500g)", "buyingPrice": "₹85", "sellingPrice": "₹0.50/pcs,170/kg", "unit": "Piece", "nos": 170},
    {"sno": 22, "productName": "Washer 4 Suta (500g)", "buyingPrice": "₹100", "sellingPrice": "₹0.50/pcs,200/kg", "unit": "Piece", "nos": 200},
    {"sno": 23, "productName": "Grinder Machine", "buyingPrice": "₹2500", "sellingPrice": "₹1500", "unit": "Piece", "nos": 2}
  ],
  "Chapakal Items": [
    {"sno": 1, "productName": "Hand Pump 4 No", "buyingPrice": "₹2500", "sellingPrice": "₹1400-1500", "unit": "Piece", "nos": 2},
    {"sno": 2, "productName": "Chapakal Chadi 3 Suta", "buyingPrice": "₹150", "sellingPrice": "₹30", "unit": "Piece", "nos": 6},
    {"sno": 3, "productName": "Planzer 4 No", "buyingPrice": "₹300", "sellingPrice": "₹60-70", "unit": "Piece", "nos": 6},
    {"sno": 4, "productName": "Valve (Buray) 4 No", "buyingPrice": "₹300", "sellingPrice": "₹30-35", "unit": "Piece", "nos": 12},
    {"sno": 5, "productName": "Washer 4 No (PVC)", "buyingPrice": "₹140", "sellingPrice": "₹20-25", "unit": "Piece", "nos": 12},
    {"sno": 6, "productName": "Valve 4 No (Camel)", "buyingPrice": "₹180", "sellingPrice": "₹15", "unit": "Piece", "nos": 12},
    {"sno": 7, "productName": "Bolt & Nut (Valve)", "buyingPrice": "₹180", "sellingPrice": "₹5", "unit": "Piece", "nos": 12}
  ],
  "Nut/Bolt/Screw/Chemical/Screw/Kanti/Carpenter": [
    {"sno": 1, "productName": "Hex Nipple ½\"", "buyingPrice": "₹200", "sellingPrice": "₹30", "unit": "Per Pcs", "nos": 10},
    {"sno": 2, "productName": "Extension Nipple ½\"", "buyingPrice": "₹300", "sellingPrice": "₹50", "unit": "Per Pcs", "nos": 10},
    {"sno": 3, "productName": "Vetra (Adhesive)", "buyingPrice": "₹280", "sellingPrice": "₹80", "unit": "Per Pcs", "nos": 4},
    {"sno": 4, "productName": "Feviquick", "buyingPrice": "₹50", "sellingPrice": "₹5", "unit": "Per Pcs", "nos": 15},
    {"sno": 5, "productName": "Fastener (Basin)", "buyingPrice": "₹250", "sellingPrice": "₹50", "unit": "Per Pkt", "nos": 10},
    {"sno": 6, "productName": "Steel Screw ½\"", "buyingPrice": "₹340", "sellingPrice": "₹1.70-2", "unit": "Per Pcs", "nos": 200},
    {"sno": 7, "productName": "Black Dry Screw ½\"", "buyingPrice": "₹250", "sellingPrice": "₹1,36/dzn", "unit": "Per Pcs", "nos": 500},
    {"sno": 8, "productName": "Rawal Plug (Gitti) (PVC)", "buyingPrice": "₹200", "sellingPrice": "₹1/pcs,24/dzn", "unit": "Per Pcs", "nos": 200},
    {"sno": 9, "productName": "Bolt 3-sut ¾\"", "buyingPrice": "₹85", "sellingPrice": "₹5", "unit": "Per Pcs", "nos": 1},
    {"sno": 10, "productName": "Bolt 4-sut ¾\"", "buyingPrice": "₹85", "sellingPrice": "₹4", "unit": "Per Pcs", "nos": 1},
    {"sno": 11, "productName": "Nut 3-sut", "buyingPrice": "₹95", "sellingPrice": "₹4", "unit": "Per Pcs", "nos": 500},
    {"sno": 12, "productName": "Nut 4-sut", "buyingPrice": "₹95", "sellingPrice": "₹4", "unit": "Per Pcs", "nos": 550},
    {"sno": 13, "productName": "Katti 1½\"", "buyingPrice": "₹80", "sellingPrice": "₹80", "unit": "Per KG", "nos": 6},
    {"sno": 14, "productName": "Katti 2\"", "buyingPrice": "₹80", "sellingPrice": "₹80", "unit": "Per KG", "nos": 6},
    {"sno": 15, "productName": "Katti 2½\"", "buyingPrice": "₹80", "sellingPrice": "₹85", "unit": "Per KG", "nos": 6},
    {"sno": 16, "productName": "Harpic 250 ML", "buyingPrice": "₹35", "sellingPrice": "₹35", "unit": "Per Bottle", "nos": 10},
    {"sno": 17, "productName": "Harpic 500 ML", "buyingPrice": "₹70", "sellingPrice": "₹70", "unit": "Per Bottle", "nos": 10},
    {"sno": 18, "productName": "Black Dry Screw ¾\"", "buyingPrice": "₹280", "sellingPrice": "₹1.50/pcs,36/dzn", "unit": "Per Pcs", "nos": 500},
    {"sno": 19, "productName": "Ring Curtain (Steel)", "buyingPrice": "₹250", "sellingPrice": "₹4/pcs,36/dzn", "unit": "Per Pcs", "nos": 250},
    {"sno": 20, "productName": "Ring Curtain (PVC)", "buyingPrice": "₹200", "sellingPrice": "₹4/pcs,24/dzn", "unit": "Per Pcs", "nos": 200},
    {"sno": 21, "productName": "Kabza (Hingis) 4\"", "buyingPrice": "₹500", "sellingPrice": "₹40", "unit": "Per Pcs", "nos": 20},
    {"sno": 22, "productName": "Kabza (Hingis) 5\"", "buyingPrice": "₹700", "sellingPrice": "₹60", "unit": "Per Pcs", "nos": 20},
    {"sno": 23, "productName": "Muthiya – 6\"", "buyingPrice": "₹200", "sellingPrice": "₹35", "unit": "Per Pcs", "nos": 200},
    {"sno": 24, "productName": "Tower Bolt – 3\"", "buyingPrice": "₹240", "sellingPrice": "₹45-50", "unit": "Per Pcs", "nos": 240},
    {"sno": 25, "productName": "Tower Bolt – 6\"", "buyingPrice": "₹840", "sellingPrice": "₹90-120", "unit": "Per Pcs", "nos": 840},
    {"sno": 26, "productName": "Door Handle -10", "buyingPrice": "₹880", "sellingPrice": "₹150-180", "unit": "Per Pcs", "nos": 880},
    {"sno": 27, "productName": "Door Bolt", "buyingPrice": "₹450", "sellingPrice": "₹7-8", "unit": "Per Pcs", "nos": 450},
    {"sno": 28, "productName": "Cover Block", "buyingPrice": "₹1200", "sellingPrice": "₹250-300", "unit": "Per Box", "nos": 1200},
    {"sno": 29, "productName": "Muthiya – 4\"", "buyingPrice": "₹150", "sellingPrice": "₹22-25", "unit": "Per Pcs", "nos": 10}
  ],
  "Grinder Wheel, Glue-Solution-Solvent Clampu": [
    {"sno": 1, "productName": "Wheel cutter (wall) 4\"", "buyingPrice": "₹700", "sellingPrice": "₹90-100", "unit": "pcs", "nos": 10},
    {"sno": 2, "productName": "Wheel cutter (wall) 5\"", "buyingPrice": "₹1000", "sellingPrice": "₹110-120", "unit": "pcs", "nos": 10},
    {"sno": 3, "productName": "Wheel cutter (Rod)", "buyingPrice": "₹400", "sellingPrice": "₹10-15", "unit": "pcs", "nos": 50},
    {"sno": 4, "productName": "Wheel Buffing", "buyingPrice": "₹280", "sellingPrice": "₹33-35", "unit": "pcs", "nos": 10},
    {"sno": 5, "productName": "Wheel Lohaghisai", "buyingPrice": "₹280", "sellingPrice": "₹30-35", "unit": "pcs", "nos": 10},
    {"sno": 6, "productName": "Wheel Wood cutter 4\"", "buyingPrice": "₹420", "sellingPrice": "₹100-110", "unit": "pcs", "nos": 6},
    {"sno": 7, "productName": "Wheel Wood cutter 5\"", "buyingPrice": "₹540", "sellingPrice": "₹110-120", "unit": "pcs", "nos": 6},
    {"sno": 8, "productName": "SWR - Solvent", "buyingPrice": "₹375", "sellingPrice": "₹75-80", "unit": "100mL", "nos": 6},
    {"sno": 9, "productName": "CPVC - Solvent", "buyingPrice": "₹1009", "sellingPrice": "₹180-190", "unit": "100mL", "nos": 6},
    {"sno": 10, "productName": "UPVC - Solvent", "buyingPrice": "₹835", "sellingPrice": "₹150-160", "unit": "100mL", "nos": 6},
    {"sno": 11, "productName": "UPVC - Solvent", "buyingPrice": "₹420", "sellingPrice": "₹45-50", "unit": "29mL", "nos": 10},
    {"sno": 12, "productName": "UPVC - Solvent", "buyingPrice": "₹400", "sellingPrice": "₹20-30", "unit": "20mL", "nos": 25},
    {"sno": 13, "productName": "CPVC - Solvent", "buyingPrice": "₹400", "sellingPrice": "₹20-30", "unit": "20mL", "nos": 25},
    {"sno": 14, "productName": "SWR - Solvent", "buyingPrice": "₹400", "sellingPrice": "₹300", "unit": "15ml", "nos": 25},
    {"sno": 15, "productName": "Fevi cool", "buyingPrice": "₹336", "sellingPrice": "₹85-105", "unit": "250gm", "nos": 4},
    {"sno": 16, "productName": "Fevi cool", "buyingPrice": "₹184", "sellingPrice": "₹50-60", "unit": "125gm", "nos": 4},
    {"sno": 17, "productName": "Flex kwik", "buyingPrice": "₹600", "sellingPrice": "₹60-65", "unit": "pcs", "nos": 10},
    {"sno": 18, "productName": "Putty plumber", "buyingPrice": "₹320", "sellingPrice": "₹15-20", "unit": "40gm", "nos": 20},
    {"sno": 19, "productName": "MCL", "buyingPrice": "₹240", "sellingPrice": "₹6", "unit": "pcs", "nos": 60},
    {"sno": 20, "productName": "SWR Pipe Clampu-\"4\"", "buyingPrice": "₹650", "sellingPrice": "₹15-18", "unit": "pcs", "nos": 50},
    {"sno": 21, "productName": "SWR Pipe Clampu-\"3\"", "buyingPrice": "₹500", "sellingPrice": "₹10-15", "unit": "pcs", "nos": 50},
    {"sno": 22, "productName": "UPVC Pipe Clampu-\"1\"", "buyingPrice": "₹260", "sellingPrice": "₹2-4", "unit": "pcs", "nos": 100},
    {"sno": 23, "productName": "UPVC Pipe Clamp- 3/4", "buyingPrice": "₹220", "sellingPrice": "₹2-3", "unit": "pcs", "nos": 100},
    {"sno": 24, "productName": "CPVC Pipe Clamp- \"1\"", "buyingPrice": "₹280", "sellingPrice": "₹3-4", "unit": "pcs", "nos": 100},
    {"sno": 25, "productName": "CPVC Pipe Clamp- 3/4", "buyingPrice": "₹280", "sellingPrice": "₹3-4", "unit": "pcs", "nos": 100},
    {"sno": 26, "productName": "Pipe clamp (SS) -1", "buyingPrice": "₹350", "sellingPrice": "₹3-4", "unit": "pcs", "nos": 100},
    {"sno": 27, "productName": "Pipe clamp (SS) - 3/4", "buyingPrice": "₹300", "sellingPrice": "₹3-4", "unit": "pcs", "nos": 100},
    {"sno": 28, "productName": "Karkat U clamp", "buyingPrice": "₹300", "sellingPrice": "₹100", "unit": "pcs", "nos": 60},
    {"sno": 29, "productName": "Karkat - Nut & Washer", "buyingPrice": "₹70", "sellingPrice": "₹7", "unit": "pcs", "nos": 50},
    {"sno": 30, "productName": "Silicon bottle", "buyingPrice": "₹720", "sellingPrice": "₹150", "unit": "Bottle", "nos": 6}
  ],
  "Sanitary Fitting": [
    {"sno": 1, "productName": "Water Tank - (Aashirwad)", "buyingPrice": "₹7400", "sellingPrice": "₹7700", "unit": "1000Ltrs", "nos": 1},
    {"sno": 2, "productName": "Water Tank - (ashirwad)", "buyingPrice": "₹3700", "sellingPrice": "₹4000", "unit": "500ltrs", "nos": 1},
    {"sno": 3, "productName": "Water Pump - Motor (1HP{6700})koel", "buyingPrice": "₹2800", "sellingPrice": "₹3500", "unit": "pcs", "nos": 1},
    {"sno": 4, "productName": "Water Pump - Motor (1HP{5400})Crompton", "buyingPrice": "₹3050", "sellingPrice": "₹3400", "unit": "pcs", "nos": 1},
    {"sno": 5, "productName": "Water Pump - Motor (1HP{5830}) havells", "buyingPrice": "₹3150", "sellingPrice": "₹3600", "unit": "pcs", "nos": 1},
    {"sno": 6, "productName": "Pressure Pipe (Garden) Roll - 5", "buyingPrice": "₹1700", "sellingPrice": "₹400-450", "unit": "pcs", "nos": 5},
    {"sno": 7, "productName": "Pressure Nipple(jointer)", "buyingPrice": "₹220", "sellingPrice": "₹12", "unit": "pcs", "nos": 10},
    {"sno": 8, "productName": "Nabdani Jalli (Strainer) -4", "buyingPrice": "₹360", "sellingPrice": "₹40", "unit": "pcs", "nos": 12},
    {"sno": 9, "productName": "Nabdani Jalli (Strainer) -3", "buyingPrice": "₹280", "sellingPrice": "₹25", "unit": "pcs", "nos": 12},
    {"sno": 10, "productName": "Shower jhrana (Steel)", "buyingPrice": "₹1312", "sellingPrice": "₹480-490", "unit": "pcs", "nos": 3},
    {"sno": 11, "productName": "Shower jhrana (Plastic)", "buyingPrice": "₹300", "sellingPrice": "₹175-200", "unit": "pcs", "nos": 3},
    {"sno": 12, "productName": "Hand Spray", "buyingPrice": "₹760", "sellingPrice": "₹450-500", "unit": "pcs", "nos": 2},
    {"sno": 13, "productName": "Waste Jalli - (Basin)", "buyingPrice": "₹420", "sellingPrice": "₹100-120", "unit": "pcs", "nos": 6},
    {"sno": 14, "productName": "Sink Jalli - (Kitchen)", "buyingPrice": "₹420", "sellingPrice": "₹100-120", "unit": "pcs", "nos": 6},
    {"sno": 15, "productName": "Waste Pipe - (Basin/Kitchen) -\"1/4\"", "buyingPrice": "₹450", "sellingPrice": "₹50", "unit": "pcs", "nos": 10},
    {"sno": 16, "productName": "Waste Pipe - (Basin/Kitchen) -\"1/2\"", "buyingPrice": "₹480", "sellingPrice": "₹55", "unit": "pcs", "nos": 10},
    {"sno": 17, "productName": "Connection Pipe - Nos-6 - \"36\"", "buyingPrice": "₹300", "sellingPrice": "₹70-80", "unit": "pcs", "nos": 6},
    {"sno": 18, "productName": "Connection Pipe - Nos-6 - \"24\"", "buyingPrice": "₹270", "sellingPrice": "₹65-70", "unit": "pcs", "nos": 6},
    {"sno": 19, "productName": "Connection Pipe - Nos-6 - \"18\"", "buyingPrice": "₹240", "sellingPrice": "₹55-60", "unit": "pcs", "nos": 6},
    {"sno": 20, "productName": "Towel Rod", "buyingPrice": "₹1280", "sellingPrice": "₹425-450", "unit": "pcs", "nos": 4},
    {"sno": 21, "productName": "Sabondani (Soap Disc)", "buyingPrice": "₹720", "sellingPrice": "₹150-200", "unit": "pcs", "nos": 6},
    {"sno": 22, "productName": "W.C. - (HIND) Seat", "buyingPrice": "₹2300", "sellingPrice": "₹1300-1350", "unit": "pcs", "nos": 2},
    {"sno": 23, "productName": "W.C. - (TORVENT) Seat", "buyingPrice": "₹1900", "sellingPrice": "₹1150-1200", "unit": "pcs", "nos": 2},
    {"sno": 24, "productName": "W.C. - (SUPRIME) Seat", "buyingPrice": "₹1500", "sellingPrice": "₹1250-1300", "unit": "pcs", "nos": 2},
    {"sno": 25, "productName": "E.W.C. - (ENGLISH) Seat", "buyingPrice": "₹4800", "sellingPrice": "₹6500", "unit": "pcs", "nos": 1},
    {"sno": 26, "productName": "Wash Basin (Pedestal)", "buyingPrice": "₹2400", "sellingPrice": "₹1400-1500", "unit": "pcs", "nos": 2},
    {"sno": 27, "productName": "Wash Basin (Small)", "buyingPrice": "₹1500", "sellingPrice": "₹950-980", "unit": "pcs", "nos": 2},
    {"sno": 28, "productName": "Flush Tank (HIND)", "buyingPrice": "₹1500", "sellingPrice": "₹900-950", "unit": "pcs", "nos": 2},
    {"sno": 29, "productName": "Flush Tank (Hindustan)", "buyingPrice": "₹900", "sellingPrice": "₹550-600", "unit": "pcs", "nos": 2},
    {"sno": 30, "productName": "Mirror", "buyingPrice": "₹1000", "sellingPrice": "₹350-380", "unit": "pcs", "nos": 4},
    {"sno": 31, "productName": "corner rok (GOYALS)", "buyingPrice": "₹720", "sellingPrice": "₹250-280", "unit": "pcs", "nos": 4},
    {"sno": 32, "productName": "nabdani jaali cut", "buyingPrice": "₹220", "sellingPrice": "₹20-25/pcs", "unit": "pcs", "nos": 31}
  ]
};

